FROM python:3.10-slim

# Configura o diretório de trabalho
WORKDIR /app

# Copiar dependências do projeto
COPY requirements.txt .

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código para o contêiner
COPY . .

# Expõe a porta usada pelo Flask
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
