# Defina o diretório público do Apache
FROM php:8.3-apache

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Configuração do PHP
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Instalar Curl
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    pkg-config \
    libssl-dev && \
    curl -LO https://curl.se/download/curl-8.9.1.tar.gz && \
    tar -xzf curl-8.9.1.tar.gz && \
    cd curl-8.9.1 && \
    ./configure --with-ssl && \
    make && \
    make install

# Instalar pacotes adicionais necessários
RUN apt-get -y update && apt-get install -y libicu-dev libzip-dev zip libjpeg-dev libpng-dev libfreetype6-dev git && \
    docker-php-ext-configure intl && \
    docker-php-ext-configure gd --with-jpeg --with-freetype && \
    docker-php-ext-install intl opcache pdo_mysql zip gd

RUN a2enmod rewrite

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN curl -sS https://get.symfony.com/cli/installer | bash && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony
RUN composer global require laravel/installer

# Instalar NVM
RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

# Limpeza de pacotes temporários
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Expose which ports will be used
EXPOSE 80
EXPOSE 3307