version: '3'
services:
  crm-app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: crm-py
    ports:
      - "5000:5000"
    volumes:
      - ./api:/crm/api
      - ./model:/crm/model
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=docker
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=crm_db
    depends_on:
      - crm-database

  crm-database:
    image: mysql:latest
    container_name: crm-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: crm_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
