version: '3'
services:
  crm-app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: crm-app
    ports:
      - "5000:5000"
    volumes:
      - ./api:/crm/api
      - ./model:/crm/model
    depends_on:
      - crm-database
    networks:
      - crm-network
  crm-database:
    image: mysql:latest
    container_name: crm-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: crm_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
    volumes:
      - database:/var/lib/mysql
    networks:
      - crm-network
networks:
  crm-network:
    driver: bridge

volumes:
  database:
