FROM python:3.10

# Define workdir
WORKDIR /crm

# Copy environment files
COPY .env.example /crm/.env

# Copy api/ to container
COPY api /crm/api

# Install api dependencies
RUN cd /crm/api && pip install -r requirements.txt
RUN cd ..

# Copy model/ to container
COPY model /crm/model

# Expose port 5000 for flask
EXPOSE 5000

# Run application
CMD ["python", "api/main.py"]
