FROM python:3.10

# Define workdir
WORKDIR /crm

# Copy environment files
COPY .env /crm/.env

# Copy api/ to container
COPY api /crm/api

# Copy model/ to container
COPY model /crm/model

# Install api dependencies
RUN pip install flask \
    && pip install python-dotenv \
    && pip install mysql-connector-python 

# Expose port 5000 for flask
EXPOSE 5000

# Run application
CMD ["python", "api/main.py"]
