  name: SI-CRM

  on:
    pull_request:
      branches:
        - '**'

  jobs:
    composer-pkg-updates:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            extensions: mbstring, intl, pdo, pdo_mysql, xdebug
            coverage: xdebug

        - name: Copy .env.example to .env
          run: | 
            cd api 
            cp .env.example .env

        - name: Install Composer dependencies
          run: | 
            cd api
            composer install --prefer-dist --no-progress --no-suggest

        - name: Check which packages could be updated
          run: |
            cd api
            echo "Checking for outdated dependencies..."
            composer outdated --strict --direct --locked || true
    composer-validate:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            extensions: mbstring, intl, pdo, pdo_mysql, xdebug
            coverage: xdebug

        - name: Copy .env.example to .env
          run: |
            cd api
            cp .env.example .env

        - name: Install Composer dependencies
          run: |
            cd api
            composer install --prefer-dist --no-progress --no-suggest

        - name: Running Composer Validate
          run: |
            cd api
            composer validate
            
    environment:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, pdo, pdo_mysql, xdebug
          coverage: xdebug

      - name: Copy .env.example to .env
        run: |
          cd api
          cp .env.example .env

      - name: Install Composer dependencies
        run: |
          cd api
          composer install --prefer-dist --no-progress --no-suggest

    unit-tests:
      runs-on: ubuntu-latest
      needs:
        - environment

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, pdo, pdo_mysql, xdebug
          coverage: xdebug

      - name: Copy .env.example to .env
        run: |
          cd api
          cp .env.example .env

      - name: Install Composer dependencies
        run: |
          cd api
          composer install --prefer-dist --no-progress --no-suggest

      - name: Run Unit Tests
        run: |
          cd api
          php artisan test

    php-cs-fixer:
      runs-on: ubuntu-latest
      needs:
        - unit-tests

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, pdo, pdo_mysql, xdebug
          coverage: xdebug

      - name: Copy .env.example to .env
        run: |
          cd api
          cp .env.example .env

      - name: Install Composer dependencies
        run: |
          cd api
          composer install --prefer-dist --no-progress --no-suggest

      - name: Run php-cs-fixer
        run: |
          cd api
          vendor/bin/php-cs-fixer check --diff
      
    phplint:
      runs-on: ubuntu-latest
      needs: 
        - environment
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            extensions: mbstring, intl, pdo, pdo_mysql, xdebug
            coverage: xdebug

        - name: Copy .env.example to .env
          run: |
            cd api
            cp .env.example .env

        - name: Install Composer dependencies
          run: |
            cd api
            composer install --prefer-dist --no-progress --no-suggest

        - name: Running PHPLint
          run: |
            cd api
            vendor/bin/phplint --configuration=phplint.json